version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 54328:5432
    environment:
      POSTGRES_DB: 'library_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'qwerty'

  backend:
    build: .
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "python manage.py migrate && 
             gunicorn config.wsgi -b 0.0.0.0:8080"
    environment:
      DJANGO_SETTINGS_MODULE: config.production

  nginx:
    build: ./nginx
    privileged: true
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend
